# Generated by Django 3.1.4 on 2020-12-14 19:48

from django.db import migrations, models
import django_dropbox_storage.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DropboxFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(storage=django_dropbox_storage.storage.DropboxStorage(), upload_to='photos')),
            ],
        ),
    ]
